name: Python Code Quality and Deployment Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

jobs:
  quality-checks:
    name: Quality Checks (Python ${{ matrix.python-version }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black mypy pytest pytest-cov
        pip install -e .

    - name: Run tests with pytest
      run: |
        pytest tests/ --cov=src --cov-report=xml

    - name: Run flake8 linting
      run: |
        flake8 src/ tests/ --count --show-source --statistics --exclude=.git,__pycache__,*/__init__.py

    - name: Run black formatting check
      run: |
        black --check src/ tests/ --exclude='/(\.git|__pycache__)/'

    - name: Run mypy type checking
      run: |
        mypy src/ tests/ --ignore-missing-imports --exclude '/(\.git|__pycache__)/'

  develop-deploy:
    name: Deploy to Development Environment
    needs: quality-checks
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/develop'
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install package
      run: |
        pip install .
        
    - name: Verify deployment
      run: |
        echo "✅ Successfully deployed to DEVELOPMENT environment"
        echo "Running smoke tests..."
        python -c "from src.calculator import add, subtract; print(f'2+3={add(2,3)}, 5-2={subtract(5,2)}')"

  production-deploy:
    name: Deploy to Production Environment
    needs: quality-checks
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install package
      run: |
        pip install .
        
    - name: Verify production deployment
      run: |
        echo "🚀 PRODUCTION DEPLOYMENT SUCCESSFUL"
        echo "Running production verification..."
        python -c "from src.calculator import add, subtract; print(f'PRODUCTION: 2+3={add(2,3)}, 5-2={subtract(5,2)}')"
