name: Python Code Quality and Simple Deployment

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality-checks:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8", "3.9", "3.10"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 black mypy pytest

    - name: Run tests
      run: |
        pytest tests/

    - name: Run quality checks
      run: |
        flake8 src/ tests/ --count --show-source --statistics --exclude=.git,__pycache__,*/__init__.py
        black --check src/ tests/ --exclude='/(\.git|__pycache__)/'
        mypy src/ tests/ --ignore-missing-imports --exclude '/(\.git|__pycache__)/'

  simple-deploy:
    needs: quality-checks
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.event_name == 'pull_request'

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install calculator locally
      run: |
        pip install .

        echo "Calculator installed successfully!"
        echo "Test usage:"
        python -c "from calc.calculator import add, subtract; print(f'2+3={add(2,3)}, 5-2={subtract(5,2)}')"
